version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes: 
      - /app/node_modules # Do not map container folder node_modules to any local
      - .:/app # Map all contents from current directory
    
    tests:
      build:
        context: .
        dockerfile: Dockerfile.dev
      volumes:
        - /app/node_modules # Do not map container folder node_modules to any local
        - .:/app # Map all contents from current directory
      command: ["npm", "run", "test"]
